In [6]:
import numpy as np

## create array using numpy

## create a one D array

arr1 = np.array([1,2,3])

print(arr1)

print(type(arr1))
print(arr1.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [12]:
# Two Dimensional array.
arr2 = np.array([1,2,3,4,5,6,7])
arr2.reshape(1,7) ## one row and 7 columns.


array([[1, 2, 3, 4, 5, 6, 7]])

In [15]:
arr3=np.array([[1,2,3,4,5]])
print(arr3)
print(arr3.shape)

[[1 2 3 4 5]]
(1, 5)


In [23]:
arr4 = np.array([[1,2,3,4],[6,7,8,9]])
print(arr4)
print(arr4.shape)

[[1 2 3 4]
 [6 7 8 9]]
(2, 4)


In [25]:
## Arrange function.

np.arange(1,20,5)

array([ 1,  6, 11, 16])

In [26]:
# Changing from one dimensional array to two dimentionsal array.
np.arange(1,20,5).reshape(1,4)

array([[ 1,  6, 11, 16]])

In [27]:
# Two D array.
np.arange(1,20,5).reshape(4,1)

array([[ 1],
       [ 6],
       [11],
       [16]])

In [32]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
## Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:

## Attributes of array.

my_arr = np.array([[1,2,3],[7,8,9]])

print("This is my array:", my_arr)
print("The shape of my array is: ", my_arr.shape)
print("The number of dimension of array is: ", my_arr.ndim)
print("The number of elements in my array is: ", my_arr.size)
print("The data type of array: ", my_arr.dtype)
print("Total item size in the array: ", my_arr.itemsize)

This is my array: [[1 2 3]
 [7 8 9]]
The shape of my array is:  (2, 3)
The dimension of array is:  2
The size of my array is:  6
The type of array:  int64
Total item size in the array:  8


In [38]:
## Numpy vectorized operation.

arr1 = np.array([[1,2,3]])

arr2 = np.array([[11,12,13]])

## Elementwise addition.
print("Addition:", arr1 + arr2)

print("Substraction", arr1-arr2)

print("Multiplication", arr1*arr2)

print("Divison", arr1/arr2)


Addition: [[12 14 16]]
Substraction [[-10 -10 -10]]
Multiplication [[11 24 39]]
Divison [[0.09090909 0.16666667 0.23076923]]


In [40]:
## Universal function.

arr = np.array([[3,6,9,12]])

## Square of array
print(np.square(arr))

## Exponencial of array
print(np.exp(arr))

##natual log.
print(np.log(arr))




[[  9  36  81 144]]
[[2.00855369e+01 4.03428793e+02 8.10308393e+03 1.62754791e+05]]
[[1.09861229 1.79175947 2.19722458 2.48490665]]


In [62]:
## array slicing and indexing.

arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print("Array: \n",arr)

Array: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [63]:
arr[0]

array([1, 2, 3, 4, 5])

In [58]:
print(arr[0][2])

3


In [59]:
arr[1:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [61]:
print(arr)

print("\n")

print(arr[1:2])

print("\n")

print(arr[1:,2:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


[[ 6  7  8  9 10]]


[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [64]:
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [65]:
## Select the second row.
print(arr[1])

[ 6  7  8  9 10]


In [66]:
# Select the second row and third row.
print(arr[1:3])

[[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [68]:
#select the second column.
print(arr[:,1])

[ 2  7 12 17]


In [69]:
#select the second and third columns
print(arr[:,1:3])

[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]]


In [80]:
print(arr)

print("\n")

print(arr[1:4,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [81]:
#Sub array of array
print(arr[1:4][1:4])

[[11 12 13 14 15]
 [16 17 18 19 20]]


In [82]:
## MModified the array element.

arr[0,0]=100

print(arr)

[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]]


In [84]:
## Staistical concepts - Normalization.
## to have mean of zero and one standard deviation.

data = np.array([1,2,3,4,5])

mean = np.mean(data)
std = np.std(data)

normalised_data = (data - mean) / std

print(normalised_data)



[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [87]:
print(np.mean(data))

print(np.median(data))


print(np.std(data))

print(np.var(data))

3.0
3.0
1.4142135623730951
2.0


In [88]:
## Logical operation

data = np.array([1,2,3,4,5,6,7,8,9])

data>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [100]:
data[(data>5) & (data<9)]

array([6, 7, 8])